//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOG
    {
        public int LogID { get; set; }
        public string ActionCode { get; set; }
        public Nullable<System.DateTime> AcTionTime { get; set; }
        public string PerformedBy { get; set; }
        public string Description { get; set; }
    }
}
