//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO
    {
        public string MABAOCAO { get; set; }
        public string BCNS { get; set; }
        public string BCTC { get; set; }
        public string BCTH { get; set; }
        public string MADN { get; set; }
    
        public virtual THONGTINDOANHNGHIEP THONGTINDOANHNGHIEP { get; set; }
    }
}
