//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public string MANV { get; set; }
        public System.DateTime NGAYCC { get; set; }
        public Nullable<System.TimeSpan> GIOVAO { get; set; }
        public Nullable<System.TimeSpan> GIORA { get; set; }
        public Nullable<double> GIOCONG { get; set; }
        public Nullable<double> TANGCA { get; set; }
        public Nullable<double> TONGCA { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
