//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPDUAN
    {
        public string MADA { get; set; }
        public string MANHAP { get; set; }
        public string MAVC { get; set; }
        public Nullable<decimal> HSTHAYDOI { get; set; }
        public Nullable<decimal> CHIPHITONG { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        public virtual NHAPNVL NHAPNVL { get; set; }
        public virtual VANCHUYENNVL VANCHUYENNVL { get; set; }
    }
}
