//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSBANGCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSBANGCAP()
        {
            this.DSCHUYENMONs = new HashSet<DSCHUYENMON>();
        }
    
        public string MABC { get; set; }
        public string TENBC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSCHUYENMON> DSCHUYENMONs { get; set; }
    }
}
