//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCHUYENMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSCHUYENMON()
        {
            this.VITRICONGVIECs = new HashSet<VITRICONGVIEC>();
        }
    
        public string MACM { get; set; }
        public string TENCM { get; set; }
        public string CACKN { get; set; }
        public string CACBC { get; set; }
        public string CACNN { get; set; }
    
        public virtual DSBANGCAP DSBANGCAP { get; set; }
        public virtual DSKYNANG DSKYNANG { get; set; }
        public virtual DSNGONNGU DSNGONNGU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VITRICONGVIEC> VITRICONGVIECs { get; set; }
    }
}
