//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTHUONGPHAT
    {
        public string MANV { get; set; }
        public System.DateTime NGAY { get; set; }
        public string HINHTHUC { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public Nullable<double> HESOTIEN { get; set; }
        public Nullable<decimal> TONG { get; set; }
        public string NOTE { get; set; }
        public int STT { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
