//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTDICHVU
    {
        public string MADV { get; set; }
        public string MAKH { get; set; }
        public string LHDICHVU { get; set; }
        public Nullable<System.DateTime> NGAYSDDV { get; set; }
        public Nullable<decimal> GIACADUTINH { get; set; }
        public Nullable<decimal> GIACATONG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
