//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTDUAN
    {
        public string MADA { get; set; }
        public string MALH { get; set; }
        public string MAKV { get; set; }
        public string DSMARR { get; set; }
        public Nullable<decimal> HSTHAYDOI { get; set; }
        public Nullable<decimal> TIENNGHIEMTHU_TONG { get; set; }
    
        public virtual RUIRO RUIRO { get; set; }
        public virtual DUAN DUAN { get; set; }
        public virtual DTTHEOKV DTTHEOKV { get; set; }
        public virtual DTTHEOLHCT DTTHEOLHCT { get; set; }
    }
}
