//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUANTHEOHOPDONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUANTHEOHOPDONG()
        {
            this.NVTHAMGIADAs = new HashSet<NVTHAMGIADA>();
        }
    
        public string MADAHD { get; set; }
        public string MADA { get; set; }
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        public virtual HOPDONG HOPDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NVTHAMGIADA> NVTHAMGIADAs { get; set; }
    }
}
