//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSOVIECLAM
    {
        public int ID { get; set; }
        public string TENUNGVIEN { get; set; }
        public string FILETHONGTIN { get; set; }
        public string FILEBANGCAP { get; set; }
        public string FILEKHAC { get; set; }
        public string EMAIL { get; set; }
    }
}
