//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLAMVIEC
    {
        public System.DateTime NGAYLAMVIEC { get; set; }
        public string MANV { get; set; }
        public Nullable<byte> CHUNHAT { get; set; }
        public Nullable<byte> NGAYLE { get; set; }
        public Nullable<float> HESOLUONG { get; set; }
        public string NOIDUNGLAMVIEC { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
