//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public string MANV { get; set; }
        public string LOAINV { get; set; }
        public Nullable<decimal> LUONGCOBAN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
