//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CHAMCONGs = new HashSet<CHAMCONG>();
            this.DSTHUONGPHATs = new HashSet<DSTHUONGPHAT>();
            this.LICHLAMVIECs = new HashSet<LICHLAMVIEC>();
            this.NVTHAMGIADAs = new HashSet<NVTHAMGIADA>();
            this.PHONGBANs = new HashSet<PHONGBAN>();
        }
    
        public string MANV { get; set; }
        public string HOLOT { get; set; }
        public string TENNV { get; set; }
        public Nullable<short> NAMSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string MAPB { get; set; }
        public string MACV { get; set; }
        public string ANH { get; set; }
        public Nullable<System.DateTime> HDLD { get; set; }
        public string MADN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSTHUONGPHAT> DSTHUONGPHATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs { get; set; }
        public virtual LUONG LUONG { get; set; }
        public virtual NHANTHAN NHANTHAN { get; set; }
        public virtual VITRICONGVIEC VITRICONGVIEC { get; set; }
        public virtual THONGTINDOANHNGHIEP THONGTINDOANHNGHIEP { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NVTHAMGIADA> NVTHAMGIADAs { get; set; }
        public virtual THONGTINBAOHIEM THONGTINBAOHIEM { get; set; }
        public virtual THONGTINLIENHE THONGTINLIENHE { get; set; }
        public virtual THONGTINSUCKHOE THONGTINSUCKHOE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGBAN> PHONGBANs { get; set; }
    }
}
