//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANTHAN
    {
        public string MANV { get; set; }
        public string TENNT { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string QUANHE { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
