//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPNVL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAPNVL()
        {
            this.CPDUANs = new HashSet<CPDUAN>();
        }
    
        public string MANHAP { get; set; }
        public string TENNVL { get; set; }
        public Nullable<decimal> CPNHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPDUAN> CPDUANs { get; set; }
    }
}
