//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIENDICH
    {
        public string TranslateKey { get; set; }
        public string vi_VN { get; set; }
        public string en_US { get; set; }
        public string jp_JP { get; set; }
    }
}
