//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINLIENHE
    {
        public string MANV { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string FB { get; set; }
        public string X { get; set; }
        public Nullable<byte> QUEQUAN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
