//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINSUCKHOE
    {
        public string MANV { get; set; }
        public Nullable<byte> CHIEUCAO { get; set; }
        public Nullable<byte> CANNANG { get; set; }
        public string TIENSUBENH { get; set; }
        public Nullable<byte> THILUCTREN10 { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
