//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINBAOHIEM
    {
        public string MANV { get; set; }
        public string LOAIBAOHIEM { get; set; }
        public string SOBAOHIEM { get; set; }
        public Nullable<System.DateTime> THOIHAN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
