//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSVATC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SETTINGS
    {
        public int SettingId { get; set; }
        public string UserId { get; set; }
        public string ThemeCode { get; set; }
        public bool DarkMode { get; set; }
        public string LanguageCode { get; set; }
        public string FontCode { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string LayoutCode { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
